services:
  jellyfin1:
    container_name: jellyfin1
    image: jellyfin/jellyfin
    environment:
      - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      - JELLYFIN_LOG_DIR=/var/log/jellyfin
    volumes:
      - ./jellyfin1/config:/etc/jellyfin
      - ./jellyfin1/data:/var/lib/jellyfin
      - ./jellyfin1/cache:/var/cache/jellyfin
      - ./jellyfin1/logs:/var/log/jellyfin
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "5"
    ports:
      - 8097:8096
  jellyfin2:
    container_name: jellyfin2
    image: jellyfin/jellyfin
    environment:
      - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      - JELLYFIN_LOG_DIR=/var/log/jellyfin
    volumes:
      - ./jellyfin2/config:/etc/jellyfin
      - ./jellyfin2/data:/var/lib/jellyfin
      - ./jellyfin2/cache:/var/cache/jellyfin
      - ./jellyfin2/logs:/var/log/jellyfin
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "5"
    ports:
      - 8098:8096
