name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.os == 'windows-latest' && 'x86_64-pc-windows-msvc' || matrix.os == 'macos-latest' && 'x86_64-apple-darwin' || 'x86_64-unknown-linux-gnu' }}
          override: true

      - name: Build
        run: cargo build --release

      - name: Rename asset
        run: |
          if [[ "${{ runner.os }}" == "macOS" ]]; then
              mv target/release/jellyfin_pr_migration target/release/jellyfin_pr_migration-${{ github.ref_name}}-macos
          elif [[ "${{ runner.os }}" == "Linux" ]]; then
              mv target/release/jellyfin_pr_migration target/release/jellyfin_pr_migration-${{ github.ref_name}}-linux
          elif [ "${{ runner.os }}" == "Windows" ]; then
              mv target/release/jellyfin_pr_migration.exe target/release/jellyfin_pr_migration-${{ github.ref_name}}-win.exe
          else
              echo "$RUNNER_OS not supported"
              exit 1
          fi
        shell: bash

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifact
          path: |
            target/release/jellyfin_pr_migration-${{ github.ref_name}}-macos
            target/release/jellyfin_pr_migration-${{ github.ref_name}}-linux
            target/release/jellyfin_pr_migration-${{ github.ref_name}}-win.exe

  create-release:
    needs: build-release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: ./artifacts/**/*
          body: |
            Note: this was an autogenerated release based on a workflow.
          draft: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
