name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.os == 'windows-latest' && 'x86_64-pc-windows-msvc' || matrix.os == 'macos-latest' && 'x86_64-apple-darwin' || 'x86_64-unknown-linux-gnu' }}
          override: true

      - name: Build
        run: cargo build --release

      - name: Rename release asset
        run: |
          asset_path="target/release/jellyfin_pr_migration"
          asset_name="jellyfin_pr_migration"
          os_suffix=""

          if [[ "${{ runner.os }}" == "macOS" ]]; then
            os_suffix="-macos"
            mv "${asset_path}" "${asset_path}${os_suffix}"
          elif [[ "${{ runner.os }}" == "Linux" ]]; then
            os_suffix="-linux"
            mv "${asset_path}" "${asset_path}${os_suffix}"
          elif [[ "${{ runner.os }}" == "Windows" ]]; then
            os_suffix="-windows.exe" # Note the .exe
            mv "${asset_path}.exe" "target/release/${asset_name}${os_suffix}"
            asset_path="target/release/${asset_name}${os_suffix}" # Update asset_path for Windows
          else
            echo "Unsupported OS: ${{ runner.os }}"
            exit 1
          fi

          echo "Renamed asset to: ${asset_path}${os_suffix}"
          # Set an output variable for the new asset name/path if your upload action needs it
        id: rename_step

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifact
          path: |
            target/release/jellyfin_pr_migration-*

  create-release:
    needs: build-release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: ./artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
